### ISSUE TITLE
[v0.11.0] Parsing error with photo included

### ISSUE THREAD

**Issue by AndreasBilke** [scheibler/khard#80]
I have one contact vcf file with a PHOTO included. When I switched from v0.9 to 0.11, khard can no longer parse the file. I get the following error: `'str' object has no attribute 'decode'`

If I remove the PHOTO everything is fine.

The structure of the faulty entry is

```
PHOTO;ENCODING=b;TYPE=JPEG:/9j/4AAQSkZJRgABAQEAZABkAAD/2wBDAAgGBgcGBQgHBwcJ
 CQgKDBQNDAsLDBkSEw8UHRofHh0aHBwgJC4nICIsIxwcKDcpLDAxNDQ0Hyc5PTgyPC4zNDL/2w
[...]
 jcZXA4IqC2je2Z1DYjPPIzUjXDwW5WMKAw54qS4iDeIImJbO7b17UWE2yGa5MM4RA7tk8gYzj1
 p5uSxy2xCf4cU+RF8tm2jPrUBPPQUJjP/Z
```

**Comment by scheibler** [comment]
Unfortunately this is related to the underlying vobject library. Please look at
https://github.com/scheibler/khard/issues/75 and https://github.com/eventable/vobject/issues/20.

In the meantime you may use the --skip-unparsable option on the command line or the skip_unparsable
= yes line in the vcard section of the config file.

**Comment by protist** [comment]
I have this problem too. Unfortunately, if I use `--skip-unparseable`, then khard won't actually find contacts with photos, as they are obviously skipped. (For me, the contacts with photos are the ones that I use the most… that's why they have photos.) This worked fine in khard 9.0. Is there some way for khard to just skip the photo field in the meantime?

**Comment by scheibler** [comment]
I still hope, that the issue is fixed in the vobject library soon. In the meantime the only thing I
could imagine is to filter out the photo line before parsing the vcard.  But if you edit the contact
afterwards, the photo attribute would be deleted from file without warning cause it was never there
in the first place.

**Comment by Tonus1** [comment]
I personally could live with that... 

Thanks for this awesome work! 



Le 19 juil. 2016 16:07, à 16:07, Eric Scheibler <notifications@github.com> a écrit:

**Comment by protist** [comment]
Thanks @scheibler. I don't understand the backend of khard enough, but would it be possible to just store the photo attribute into a temporary string and write it back in a "dumb" way after editing the vcard?

**Comment by scheibler** [comment]
protist <notifications@github.com> schrieb am 19.07.2016, 14:57 -0700:
>I don't understand the backend of khard enough, but would it be possible to just store the photo
>attribute into a temporary string and write it back in a "dumb" way after editing the vcard?

Theoretically that would be possible. But it also would result in a very hacky solution. The
underlying problem is bigger then just the photo field. Although I've encountered no problems at
other attributes so far, that still could happen and then I would have to write an exception for
every failing attribute. Therefore I'am not very comfortable with that workaround. But I also
understand your problem.

**Comment by protist** [comment]
Yes, I totally understand. It's definitely not your job to hack around upstream issues! And I agree that it's messy at best.

I'm just worried about unintentional loss of data. Could another, less-hacky option be to just warn the user when editing that the photo attribute will be lost?

**Comment by scheibler** [comment]
protist <notifications@github.com> schrieb am 19.07.2016, 15:33 -0700:
>I'm just worried about unintentional loss of data. Could another, less-hacky option be to just warn the user when editing that the photo attribute will be lost?

Yes. I thought about that too. I'll give it a try in the next days.

**Comment by protist** [comment]
Thank you so much for your quick responses. I appreciate it. Cheers.

**Comment by scheibler** [comment]
Please try out the latest commit from the develop branch. I've integrated a workaround for the photo
attribute parsing issue. After successful editing of the contact, the photo attribute is written
back to the vcard file automatically (spares the warning dialog for the moment). Please tell me,
whether that works for you. And is the photo attribute data preserved correctly?

**Comment by AndreasBilke** [comment]
Works for me and the photo attribute is preserved (it is added at the end
of the vcard).

**Comment by protist** [comment]
Works perfectly for me too. I can view any contact (without needing `--skip-unparseable`), and existing photos in contacts are still preserved after editing. Thank you for the quick fix!

**Comment by mclbn** [comment]
Works here too. I can edit and sync contacts, not losing photos during the process. Thanks for the fix!

**Comment by protist** [comment]
(Also, is this workaround something you'll push to a tagged release, or should I just keep the develop branch installed?)

**Comment by scheibler** [comment]
I guess, that I will merge this back to master and create a release tag soon cause it's a quiet
critical bug. But for now, keep using the develop branch please.

**Comment by protist** [comment]
Thanks again. I'll do as you recommend. Cheers.

**Comment by scheibler** [comment]
released version 0.11.1
